import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import StoreProvider from "@/store/StoreProvider";
import { NavFooterLayout } from "@/components";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import "@ant-design/v5-patch-for-react-19";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <Toaster />
          <StoreProvider>
            <ConfigProvider
              theme={{
                token: {
                  colorPrimary: "#4338CA",
                },
              }}
            >
              <NavFooterLayout>{children}</NavFooterLayout>
            </ConfigProvider>
          </StoreProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
